### ISSUE TITLE
problem retrieving secrets with \n on them

### ISSUE THREAD

**Issue by pbullian** [signal-ai/signal-secret-service#1]
We have some secrets with \n on them and with this commit 6e9e1ac2ee2f1921885b087e08cfd0196cd4d838 it's failing as it can't export the secret. it's chopping them on each new line.

`secret_env=$(/chamber export $SECRET_SERVICES -f dotenv)
to_secrets=$(echo "$secret_env" | sed 's/\(=[[:blank:]]*\)\(.*\)/\1"\2"/')
`
instead of
`to_secrets=$(/chamber export $SECRET_SERVICES -f dotenv | sed 's/\(=[[:blank:]]*\)\(.*\)/\1"\2"/')	`

**Comment by fredsig** [comment]
Hi there. Can you export your secret using chamber? I want to see what is output using the dotenv format. Please obfuscate it, so the original is not shown.

chamber export service_name -f dotenv

where service_name has the path /service_name in Parameter Store. In alternative, please provide us a way to write it so we can reproduce it.

**Comment by fredsig** [comment]
Latest v1.2 release now uses a more up to date chamber version that should work well now with the dotenv format for eval exports. Please let me know if you still seeing issues with the latest.

**Comment by pbullian** [comment]
Sorry for the late reply, but yes, it's now fixed. Thank you!.
